image: node:18.12.1
stages:
  - lint

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn/cache
    - node_modules

before_script:
  - yarn install --frozen-lockfile

eslint:
  stage: lint
  variables:
    NODE_VERSION: 18.12.1
  script:
    - yarn install
    - yarn lint:eslint

check-format:
  stage: lint
  variables:
    NODE_VERSION: 18.12.1
  script:
    - yarn install
    - yarn check:format

types:
  stage: lint
  variables:
    NODE_VERSION: 18.12.1
  script:
    - yarn install
    - yarn lint:types
