image: node:18.12.1
stages:
  #  - lint
  - deploy
#
#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - .yarn/cache
#    - node_modules
#
#eslint:
#  stage: lint
#  variables:
#    NODE_VERSION: 18.12.1
#  before_script:
#    - yarn install --frozen-lockfile
#  script:
#    - yarn lint:eslint
#
#check-format:
#  stage: lint
#  variables:
#    NODE_VERSION: 18.12.1
#  before_script:
#    - yarn install --frozen-lockfile
#  script:
#    - yarn check:format
#
#types:
#  stage: lint
#  variables:
#    NODE_VERSION: 18.12.1
#  before_script:
#    - yarn install --frozen-lockfile
#  script:
#    - yarn lint:types

deploy:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | head -n 2
#    - echo '$SSH_PRIVATE_KEY' | tr -d '\r' | ssh-add -
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#    - scp . afonya@158.160.65.245:~/cicd
